name: Build Test Win32 (Debug)

on: [push, pull_request]

jobs:
  call-workflow-build:
    uses: ./.github/workflows/workflow-build-wtl-cache.yml
    with:
      platform-arch: Win32
      build-config: Debug
